### ISSUE TITLE
Add modern C++ answer

### ISSUE THREAD

**Issue by arnaud-m** [arnaud-m/echo#7]

**Comment by Mystelven** [comment]
Here is a quite modern C++ solution (with no condition on the cpp compiler required).

    #include <iostream>
    #include <string>
    #include <sstream> 

    using namespace std;

    int main() {
            
        // Vous pouvez remplacer le int par n'importe quel type primitif et le reste de la lecture ne change pas.
        int i;

        // On boucle sur l'entrée standard. On place chaque message dans la
        // string s, puis on le traite
        for (string s; getline(cin, s);) {

            // on affiche l'entier courant suivi d'une nouvelle ligne :
            // On suppose durant cette boucle, que le fichier est bien formé.
            istringstream stream(s);
            
            do {
                stream >> i;
                
                cout << i << endl;

            } while (stream.good());
        }

        return 0;
    }

If you find something strange in this code, feel free to add a comment in this issue.

**Comment by alessandrorubio** [comment]
@arnaud-m If the behavior you want is to instantly print the the command, this could do the trick:

```
#include <iostream>

using namespace std;

int main()
{
	int t;
	while (cin >> t) cout << t << endl;
	return 0;
}
```

**Comment by arnaud-m** [comment]
Yes, you are right, it is a simpler version for reading an integer stream. 
For more complicated problems, it can be useful to read the stream line by line and to treat each line separately.
